parameters:
  name: ''

steps:
  - task: GitVersion@4
    displayName: GitVersion
  - powershell: |
      ./Build-Task.ps1  -Build -TaskRoot $(System.DefaultWorkingDirectory)/tasks/${{ parameters.name }}
    displayName: "Build"
    failOnStderr: "false"
    workingDirectory:  $(System.DefaultWorkingDirectory)
  - powershell: |
      $(System.DefaultWorkingDirectory)/release/${{ parameters.name }}/tests/Start-UnitTest.ps1
    displayName: "Test"
    failOnStderr: "true"
    workingDirectory:  $(System.DefaultWorkingDirectory)    
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'NUnit'
      testResultsFiles: $(System.DefaultWorkingDirectory)/release/${{ parameters.name }}/tests/Test-Pester.XML
    displayName: "Publish results"
    condition: succeededOrFailed()
  - task: PackageVSTSExtension@1
    inputs:
      rootFolder: $(System.DefaultWorkingDirectory)/release/${{ parameters.name }}
      outputPath: $(System.DefaultWorkingDirectory)/release/bin
      updateTasksVersion: false
    displayName: "Package vsix"
  - task: CopyFiles@2
    inputs:
      Contents: |
        release/bin/*.vsix
        release/$(name)/**
      TargetFolder: "$(build.artifactstagingdirectory)/publish"
      OverWrite: true
    displayName: "Copy Files to: $(build.artifactstagingdirectory)"
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: "$(build.artifactstagingdirectory)/publish"
    displayName: "Publish Artifact"

